version: "3.5"
services:
  sample-www:
    build:
      context: .docker/www
      dockerfile: Dockerfile
      args:
        PHP_VERSION: ${PHP_VERSION}
        SITE_URL: ${SITE_URL}
    container_name: sample-www
    ports:
      - "${WWW_HTTP_PORT}:80"
      - "${WWW_HTTPS_PORT}:443"
      - 8983:8983
    volumes:
      - sample-nfsmount:/var/www/html
    networks:
      - sample
  sample-mysql:
    image: mysql:latest
    platform: linux/amd64
    container_name: sample-mysql
    ports:
      - "3306:3306"
    volumes:
      - sample-mysqldata:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=sampleDB
      - TZ=Pacific/Auckland
    networks:
      - sample
networks:
  sample:
    driver: "bridge"
volumes:
  sample-mysqldata:
    driver: "local"
  sample-nfsmount:
    driver: local
    driver_opts:
      type: nfs
      o: addr=host.docker.internal,rw,nolock,hard,nointr,nfsvers=3
      device: ":${PWD}"
